PACKAGE_NAME="uwe5622"
MAKE[0]="make"
BUILT_MODULE_NAME[0]="uwe5622_bsp_sdio"
BUILT_MODULE_NAME[1]="sprdwl_ng"
BUILT_MODULE_NAME[2]="sprdbt_tty"
BUILT_MODULE_NAME[3]="bluetooth_sprd"
BUILT_MODULE_LOCATION[0]="uwe5622/unisocwcn/"
BUILT_MODULE_LOCATION[1]="uwe5622/unisocwifi"
BUILT_MODULE_LOCATION[2]="uwe5622/tty-sdio"
BUILT_MODULE_LOCATION[3]="bluetooth"
DEST_MODULE_LOCATION[0]="/extra/unisocwcn/"
DEST_MODULE_LOCATION[1]="/extra/unisocwifi/"
DEST_MODULE_LOCATION[2]="/extra/tty-sdio/"
DEST_MODULE_LOCATION[3]="/extra/bluetooth/"
PACKAGE_VERSION="1.1"
AUTOINSTALL="yes"
